name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger only when a PR is merged into main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Step 3: Run Normal Build
      - name: Run Build
        run: npm run build  # Replace with your specific build command

  docker-image:
    runs-on: ubuntu-latest
    needs: build  # This job waits for the 'build' job to finish successfully

    steps:
      # # Step 1: Checkout code again, needed because each job runs in a fresh environment
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # Step 2: Build the Docker Image
      - name: Build Docker image
        run: docker build -t my-local-image:latest .


      # Step 3: Run the Docker Image
      - name: Run Docker image
        run: docker run -d -p 3000:3000 my-local-image:latest
